import Foundation
import Testing
@testable import Day8

struct Day8ExampleTests {

    @Test func exampleOne() {
        let input = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
        """

        let parseResult = InputParser(input: input).parse()
        let result = Day8(input: parseResult).part1()

        #expect(result == 14)
    }
    @Test func exampleTwo() {
        let input = """
        T.........
        ...T......
        .T........
        ..........
        ..........
        ..........
        ..........
        ..........
        ..........
        ..........
        """

        let parseResult = InputParser(input: input).parse()
        let result = Day8(input: parseResult).part2()

        #expect(result == 9)
    }
}
